### ISSUE TITLE
prod: FFx 14 - b.setStagedOnBehalfOf exception thrown when closing window

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#2072]
STR

1) Open 123done.org in FFx 14
2) Open Error Console
3) Open Persona Dialog.
4) Without selecting an email address, close the dialog.

Timestamp: 17/07/2012 17:10:18
Error: TypeError: b.setStagedOnBehalfOf is not a function
Source File: https://static.login.persona.org/v/cb8d77cc83/production/en_US/dialog.js
Line: 9

**Comment by jrgm** [comment]
This is also GH-1848

**Comment by shane-tomlinson** [comment]
@jrgm - thanks, and like #1848, this was fixed with b1f30fba, which has not yet made its way to prod.  Closing as already fixed.

**Comment by jrgm** [comment]
verified same as GH-1848. Works with no exception in train-2012.07.30
