### ISSUE TITLE
install procedure on windows shows some prerequisites missing from the install steps

### ISSUE THREAD

**Issue by Pomax** [mozilla/persona#3959]
Even with the three prerequisites installed, the `npm install` process will die on windows or OSX when it hits the bcrypt module, which tries to compile using node-gyp -- unless you have a C++ stack installed (which would ideally be listed in the prerequisites) this step will fail quite hard.

As far as browserid itself is concerned, the fact that it fails isn't really your fault, but might warrant a mention in the README.md, in the mean time I've also filed https://github.com/ncb000gt/node.bcrypt.js/issues/186 because precompiled binaries are extremely useful and make an `npm install` much easier

**Comment by seanmonstar** [comment]
As the only Windows user on the team, I hear you! If you do setup all the prerequisites, though, it _will_ install and run just fine.

**Comment by Pomax** [comment]
hmm, are you sure? I have a full vc++ (2010 express) stack on this windows machine *win7, x64), with libgmp3 (4.3.2-1) and g++ (4.7.3-1) and node 0.10.18, but when running through `npm install` the process dies when it tries to build bcrypt, citing that it can't find the `openssl/rand.h` header (there might be more unfindables, but node-gyp just dies on the first error)

```
> bcrypt@0.7.5 install C:\Users\Mike\Documents\Git projects\temp\browserid\node_modules\bcrypt
> node-gyp rebuild


C:\temp\browserid\node_modules\bcrypt>node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js
" rebuild
  blowfish.cc
  bcrypt.cc
  bcrypt_node.cc
..\src\bcrypt.cc(232): warning C4267: '=' : conversion from 'size_t' to 'unsigned char', possible loss of data [C:\temp\browserid\node_modules\bcrypt\build\bcrypt_lib.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\include\xlocale(323): warning C4530: C++ exception handler used, but unwind semantics are not enabled. Specify /EHsc [C:\temp\browserid\node_modules\bcrypt\build\bcrypt_lib.vcxproj]
..\src\bcrypt_node.cc(38): fatal error C1083: Cannot open include file: 'openssl/rand.h': No such file or directory [C:\temp\browserid\node_modules\bcrypt\build\bcrypt_lib.vcxproj]
gypnpm ERR! weird error 1
npmnpm ERR! weird error 1
npm ERR! not ok code 0
```

**Comment by seanmonstar** [comment]
Yep, I just hit that problem when I upgrade from node 0.8 to 0.10. I needed
to install OpenSSL-Win64.

**Comment by Pomax** [comment]
nice, let's see if that remedies it for me as well.

**Comment by Pomax** [comment]
actually, that's proving fairly hard to find, since openssl itself doesn't distribute it, and only lists a 32 bit version. Where did you grab OpenSSL-Win64?

**Comment by seanmonstar** [comment]
This page has them: http://slproweb.com/products/Win32OpenSSL.html

A few links down: "Win64 OpenSSL v1.0.1e"

**Comment by Pomax** [comment]
vc++ 2008  redist. and the openssl installer run, did you add anything from the openssl dir to the windows path? (I don't see node-gyp's vc++ chain picking up the openssl header files)

**Comment by seanmonstar** [comment]
yea, getting native modules to build on windows sucks. I spent a couple days slowly piecing together how from filed issues on different repos.

I grabbed VS2012, and also removed all the vc++ redist. Just tried a bunch of combos of whats described in the readme: https://github.com/TooTallNate/node-gyp

**Comment by Pomax** [comment]
that "removing all vc++" is probably the worst part of having to work with node-gyp... until sqlite3 offered binaries (thank god they do now!) getting the vc++ 2010 stack installed properly was a true journey of discovery.

I have openssl installed on its "desired" (and decidedly-non-windows) path on C:, with the vc++ 2008 redist. installed as well, with the bin dir in the PATH, and the install goes a bit further now, but still gets stuck late in the compile step: https://pastebin.mozilla.org/3225013

The line `C:\Users\Mike\.node-gyp\0.10.20\Release\node.lib : fatal error LNK1127: library is corrupt [c:\temp\browserid\node_modules\bcrypt\build\bcrypt_lib.vcxproj]` is pretty weird... =/

**Comment by Pomax** [comment]
Getting closer to having everything work; upgraded node to 0.10.20 with npm 1.3.11, a prune and cache clear later I now get to the point where bcrypt seems to compile, but the ephemeral key generator script has issues with spaces in locations:

```
c:\users\mike\documents\Git projects\temp\browserid\scripts\generate_ephemeral_keys.js:15
    if (err) throw err;
                   ^
Error: Command failed: 'c:\users\mike\documents\Git' is not recognized as an internal or external command,

operable program or batch file.


    at ChildProcess.exithandler (child_process.js:637:15)
    at ChildProcess.EventEmitter.emit (events.js:98:17)
    at maybeClose (child_process.js:735:16)
    at Socket.<anonymous> (child_process.js:948:11)
    at Socket.EventEmitter.emit (events.js:95:17)
    at Pipe.close (net.js:466:12)
```

A console.log in the generation script shows

```
file = c:\users\mike\documents\Git projects\temp\browserid\node_modules\.bin\generate-keypair
args = -k 256 -a rsa
```

If I rely on the fact that npm install occurs inside `c:\users\mike\documents\Git projects\temp\browserid` so that the file is just `node_modules\.bin\generate-keypair`, the process now finishes without error, so that part might need a filter to remove process.cwd from the `file` argument

**Comment by Pomax** [comment]
filed https://github.com/mozilla/browserid/pull/3962 for the generate_ephemeral_keys.js issue

**Comment by Pomax** [comment]
filed https://github.com/mozilla/browserid/pull/3963 for the windows-specific instructions in the docs dir

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
